# Eat Safe, Love

## Notebook Set Up

In [72]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd
from bson.son import SON

In [73]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [74]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [75]:
# review the collections in our database

collections_list = db.list_collection_names()

# Print the collections
print("Collections in the database:")
for collection in collections_list:
    print(collection)

Collections in the database:
establishments

In [76]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [77]:
# Find the establishments with a hygiene score of 20
hygiene_20_query = {"scores.Hygiene": 20}

# Use count_documents to display the number of documents in the result
hygiene_20_count = establishments.count_documents(hygiene_20_query)
print(f"Number of establishments with a hygiene score of 20: {hygiene_20_count}")

# Display the first document in the results using pprint
hygiene_20_first_doc = establishments.find_one(hygiene_20_query)
pprint(hygiene_20_first_doc)

Number of establishments with a hygiene score of 20: 41
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': {'$toInt': '$RatingValue'},
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('65b4ab94fbda4f3bc36323b6'),
 'geocode': {'latitude': {'$toDouble': '$geocode.latitude'},
             'longitude': {'$toDouble': '$geocode.longitude'}},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [78]:
# Convert the result to a Pandas DataFrame

hygiene_20_df = pd.DataFrame(list(establishments.find(hygiene_20_query)))

# Display the number of rows in the DataFrame
print(f"Number of rows in the DataFrame: {len(hygiene_20_df)}")

# Display the first 10 rows of the DataFrame
hygiene_20_df.head(10)

Number of rows in the DataFrame: 41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,65b4ab94fbda4f3bc36323b6,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,http://www.eastbourne.gov.uk/foodratings,Customerfirst@eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,{'longitude': {'$toDouble': '$geocode.longitud...,,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,65b4ab94fbda4f3bc3632737,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,{'longitude': {'$toDouble': '$geocode.longitud...,,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,65b4ab94fbda4f3bc3632a42,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,{'longitude': {'$toDouble': '$geocode.longitud...,,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,65b4ab94fbda4f3bc3632c31,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,{'longitude': {'$toDouble': '$geocode.longitud...,,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,65b4ab94fbda4f3bc3632c3e,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,{'longitude': {'$toDouble': '$geocode.longitud...,,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
5,65b4ab94fbda4f3bc36335de,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,{'longitude': {'$toDouble': '$geocode.longitud...,,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
6,65b4ab94fbda4f3bc36337ff,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,{'longitude': {'$toDouble': '$geocode.longitud...,,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
7,65b4ab95fbda4f3bc3634d2a,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,http://www.rochford.gov.uk,customerservices@rochford.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,{'longitude': {'$toDouble': '$geocode.longitud...,,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,65b4ab95fbda4f3bc363516c,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,http://www.sevenoaks.gov.uk/,environmental.health@sevenoaks.gov.uk,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,{'longitude': {'$toDouble': '$geocode.longitud...,,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,65b4ab95fbda4f3bc3635980,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,http://www.basildon.gov.uk,ehs@basildon.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,{'longitude': {'$toDouble': '$geocode.longitud...,,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [79]:
# Find the establishments with London as the Local Authority and RatingValue >= 4
london_high_rating_query = {
    "LocalAuthorityName": {"$regex": "London", "$options": "i"},
    "RatingValue": {"$gte": 4}
}

# Use count_documents to display the number of documents in the result
london_high_rating_count = establishments.count_documents(london_high_rating_query)
print(f"Number of establishments in London with RatingValue >= 4: {london_high_rating_count}")

# Display the first document in the results using pprint
london_high_rating_first_doc = establishments.find_one(london_high_rating_query)
pprint(london_high_rating_first_doc)

Number of establishments in London with RatingValue >= 4: 0
None

In [80]:
# Convert the result to a Pandas DataFrame
london_high_rating_df = pd.DataFrame(list(establishments.find(london_high_rating_query)))

# Display the number of rows in the DataFrame
print(f"Number of rows in the DataFrame: {len(london_high_rating_df)}")

# Display the first 10 rows of the DataFrame
london_high_rating_df.head(10)

Number of rows in the DataFrame: 0

Empty DataFrame
Columns: []
Index: []

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [81]:
# Coordinates for Penang Flavours
latitude_pf = float('51.49014200')
longitude_pf = float('0.08384000')

# Search within 0.01 degree on either side of the latitude and longitude.
degree_search = 0.01

# Query for establishments with RatingValue of 5, sorted by lowest hygiene score, nearest to Penang Flavours
query_pf = {
    "geocode.latitude": {"$gte": latitude_pf - degree_search, "$lte": latitude_pf + degree_search},
    "geocode.longitude": {"$gte": longitude_pf - degree_search, "$lte": longitude_pf + degree_search},
    "scores.Hygiene": {"$ne": "", "$type": 16},  # $type: 16 means the field is string
    "RatingValue": 5
}

# Print the query
print(query_pf)

{'geocode.latitude': {'$gte': 51.480142, '$lte': 51.500142}, 'geocode.longitude': {'$gte': 0.07384, '$lte': 0.09383999999999999}, 'scores.Hygiene': {'$ne': '', '$type': 16}, 'RatingValue': 5}

In [82]:
# Query for establishments with RatingValue of 5, sorted by lowest hygiene score, nearest to Penang Flavours
# Rating value must equal 5, and hygiene score must be numeric or an empty string
query_pf = {
    "geocode.latitude": {"$gte": latitude_pf - degree_search, "$lte": latitude_pf + degree_search},
    "geocode.longitude": {"$gte": longitude_pf - degree_search, "$lte": longitude_pf + degree_search},
    "$or": [
        {"scores.Hygiene": {"$exists": False}},  # Check if field does not exist
        {"scores.Hygiene": {"$type": 16}},  # Check if field is string type
        {"scores.Hygiene": {"$type": 1}},  # Check if field is double type
        {"scores.Hygiene": {"$type": 16, "$ne": ""}},  # Check if field is non-empty string
        {"scores.Hygiene": {"$type": 1, "$ne": ""}}  # Check if field is non-empty double
    ],
    "RatingValue": 5
}

# Execute the query and print the results
results_pf = establishments.find(query_pf).sort(sort_pf).limit(5)

# Display the results
for result_pf in results_pf:
    pprint(result_pf)

In [83]:
# Convert result to Pandas DataFrame
import pandas as pd

# Execute the query and store the results in a DataFrame
df_pf = pd.DataFrame(list(establishments.find(query_pf).sort(sort_pf).limit(5)))

# Display the number of rows in the DataFrame
print("Number of establishments with RatingValue 5:", len(df_pf))

# Display the first 10 rows of the DataFrame
print("First 10 rows of the DataFrame:")
print(df_pf.head(10))

Number of establishments with RatingValue 5: 0
First 10 rows of the DataFrame:
Empty DataFrame
Columns: []
Index: []

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [84]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest

# Print the number of documents in the result

# Print the first 10 results



# Create a pipeline to match establishments with a hygiene score of 0
# Group the matches by Local Authority and sort in descending order
pipeline = [
    {
        "$match": {"scores.Hygiene": 0}
    },
    {
        "$group": {
            "_id": "$LocalAuthorityName",
            "count": {"$sum": 1}
        }
    },
    {
        "$sort": SON([("count", -1)])
    }
]

# Execute the aggregation pipeline and store the results in a list
result_pipeline = list(establishments.aggregate(pipeline))

# Print the number of documents in the result
print("Number of documents with hygiene score 0:", len(result_pipeline))

# Print the first 10 results
print("First 10 results:")
for result in result_pipeline[:10]:
    pprint(result)

Number of documents with hygiene score 0: 55
First 10 results:
{'_id': 'Thanet', 'count': 1130}
{'_id': 'Greenwich', 'count': 882}
{'_id': 'Maidstone', 'count': 713}
{'_id': 'Newham', 'count': 711}
{'_id': 'Swale', 'count': 686}
{'_id': 'Chelmsford', 'count': 680}
{'_id': 'Medway', 'count': 672}
{'_id': 'Bexley', 'count': 607}
{'_id': 'Southend-On-Sea', 'count': 586}
{'_id': 'Tendring', 'count': 542}

In [86]:


# Convert the result to a Pandas DataFrame
df_result = pd.DataFrame(result_pipeline)

# Display the number of rows in the DataFrame
print("Number of rows in the DataFrame:", len(df_result))

# Display the first 10 rows of the DataFrame
print("First 10 rows of the DataFrame:")
print(df_result.head(10))

Number of rows in the DataFrame: 55
First 10 rows of the DataFrame:
               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542